### ISSUE TITLE
'context' must be object

### ISSUE THREAD

**Issue by awesomehimanshu** [awesomehimanshu/restify-validation#1]
E:\NodeProject\restify-project\node_modules\joi\lib\types\any\index.js:94
            throw new Error(result.error.details[0].message);
            ^

Error: "context" must be an object
    at checkOptions (E:\NodeProject\restify-project\node_modules\joi\lib\types\any\index.js:94:19)
    at _validateWithOptions (E:\NodeProject\restify-project\node_modules\joi\lib\types\any\index.js:657:18)
    at root.validate (E:\NodeProject\restify-project\node_modules\joi\lib\index.js:136:23)
    at validate (E:\NodeProject\restify-project\node_modules\restify-api-validation\lib\index.js:75:7)

**Comment by awesomehimanshu** [comment]
Add this option in the  json options .
options: { flatten: true , contextRequest: true}

'use strict';
```
var Joi = require('joi');

module.exports = {
  options: { contextRequest: true },
  body: {
    id: Joi.string().valid(Joi.ref('$params.id')).required()
  }
};
```
